config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  
  get 'logout' => 'sessions#destroy'
  
  post 'event_signup' => 'event_attendances#create'
  resources :users
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    has_many :event_attendances
    #has_many :users, :through => :event_attendances, :source => :user_id
    validates :name, presence: true, length: { minimum: 4, maximum: 35}
    validates :location, presence: true, length: { minimum: 4, maximum: 35}
    validate :date_on_validation
    
    def date_on_validation
        if date_on.present? && date_on < Date.today
            errors.add(:date_on, "can't be in the past")
        end
    end
end

app/models/event_attendance.rb
class EventAttendance < ActiveRecord::Base
    belongs_to :user
    belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :events
    has_many :event_attendances
    has_secure_password
    validates :name, presence: true, length: { minimum: 3, maximum: 30 }
    validates :email, presence: true, length: { minimum: 6, maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
    def create
        @event_attendance = EventAttendance.new(user_id: params[:user_id], event_id: params[:event_id])
        if @event_attendance.save
            flash[:success] = "Signed up for event successfully"
        else
            flash[:danger] = "An error occured whilst trying to sign you up for an event"
        end
        redirect_to root_url
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def new
        @event = Event.new
    end
    
    def create
        @event = User.find(session[:current_user]).events.build(event_params)
        if @event.save
            flash[:success] = "Event created successfully"
            redirect_to root_url
        else
            flash.now[:danger] = "An error(s) occured when creating the event"
            render 'new'
        end
    end        
        
    def index
        @events = Event.order('events.date_on ASC').all.paginate(page: params[:page], :per_page => 5)
    end        
   
    private
        def event_params
            params.require(:event).permit(:name, :location, :date_on)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:email].downcase)
        if user && user.authenticate(params[:password])
            session[:current_user] = user.id
            redirect_to root_url
        else
            flash.now[:danger] = 'Invalid email/password combination'
            render 'new'
        end
    end
    
    def destroy
        session[:current_user] = nil
        redirect_to root_url
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "User created successfully!"
            session[:current_user] = @user.id
            redirect_to root_url
        else 
            flash.now[:danger] = "An error(s) occured while trying to create user"
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
        
    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def logged_in?
        if session[:current_user] != nil
            return true
        else 
            return false
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event-container">
    <div class="event-content" >
    <h3><%= event.name %></h3></br>
    <p> 
        Location:
        <%= event.location %> </br>
        Date:
        <%= event.date_on %> </br>
        Organizer:
        <strong><%= User.find(event.user_id).name %></strong> </br>
        People coming to the event:
        <% @users = EventAttendance.where(event_id: event.id).all %>
        <% @users.each do |user| %>
            <%= link_to User.find(user.user_id).name, User.find(user.user_id) %>
        <% end %>
        <% if session[:current_user] != nil && EventAttendance.find_by(user_id: session[:current_user], event_id: event.id) == nil %>
            <form action="/event_signup" method="post">
                <input type="hidden" name="user_id" value="<%= session[:current_user]%>">
                <input type="hidden" name="event_id" value="<%= event.id%>">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
                <input type="submit" value="Sign up" class="btn-primary">
            </form>
        <% end %>
    </p>
    </div>
</div>

app/views/events/index.html.erb
<h2>Events:</h2>
<ul class="events">
    <%= render @events %>
</ul>
<%= will_paginate @microposts %>

app/views/events/new.html.erb
<div class="container">
    <div class="jumbotron">
    <h2>Create event:</h2>
    <%= form_for @event do |f| %>
       <%= f.label :name %></br>
       <%= f.text_field :name %></br>
       
       <%= f.label :location %></br>
       <%= f.text_field :location %></br>
       
       <%= f.label :date_on %></br>
       <%= f.date_field :date_on %></br>
       
       <%= f.submit 'Create event', class: 'btn-default' %>
    <% end %>
    </div>
</div>

app/views/layouts/_header.html.erb
<header>
    <div class="top-links">
        <%= link_to 'Home', root_url %>
        <div class="navigation">
            <% if logged_in? %>
                <%= link_to 'Profile', user_path(session[:current_user]) %>
                <%= link_to 'Create Event', new_event_path %>
                <%= link_to 'Log out', request.base_url + '/logout' %>
            <% else %>
                <%= link_to 'Log in', request.base_url + '/login' %>
                <%= link_to 'Register', new_user_path %>
            <% end %>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<!-- this creates the greeting message for successful signup -->
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>">
				<%= message %>
			</div>
		<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="container">
    <div class="jumbotron">
    <h2>Create a new account</h2>
    <%= form_for @user do |f| %>
        <%= f.label :name %></br>
        <%= f.text_field :name %></br>
        
        <%= f.label :email %></br>
        <%= f.text_field :email %></br>
        
        <%= f.label :password %></br>
        <%= f.password_field :password %></br>
        
        <%= f.label :password_confirmation %></br>
        <%= f.password_field :password_confirmation %></br>
        
        <%= f.submit 'Create user', class: 'btn-default' %>
    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <h2><%= @user.name %></h2>
    <div class="organized-events">
        <% @organized_events = Event.where(user_id: @user.id).all %>
        <% @organized_events.each do |event| %>
            <%= render event %>
        <% end %>
    </div>
    
    <div class="entered-events">
        <% @entered_events = EventAttendance.where(user_id: @user.id).all %>
        <% @entered_events.each do |entered_event| %>
            <%= render Event.find(entered_event.event_id) %>
        <% end %>
    </div>
</div>